export const GET_STOCK_DETAILS_REQUEST = 'GET_STOCK_DETAILS_REQUEST';
export const GET_STOCK_DETAILS_SUCCESS = 'GET_STOCK_DETAILS_SUCCESS';

export const SAVE_STOCK_DETAILS_REQUEST = 'SAVE_STOCK_DETAILS_REQUEST';
export const SAVE_STOCK_DETAILS_SUCCESS = 'SAVE_STOCK_DETAILS_SUCCESS';


export const GET_SAVED_STOCK_DETAILS_REQUEST = 'GET_SAVED_STOCK_DETAILS_REQUEST';
export const GET_SAVED_STOCK_DETAILS_SUCCESS = 'GET_SAVED_STOCK_DETAILS_SUCCESS';


export const GET_SAVED_STOCK_DETAILS_BY_ID_REQUEST = 'GET_SAVED_STOCK_DETAILS_BY_ID_REQUEST';
export const GET_SAVED_STOCK_DETAILS_BY_ID_SUCCESS = 'GET_SAVED_STOCK_DETAILS_BY_ID_SUCCESS';

export const DELETE_SAVED_STOCK_DETAILS_BY_ID_REQUEST = 'DELETE_SAVED_STOCK_DETAILS_BY_ID_REQUEST';
export const DELETE_SAVED_STOCK_DETAILS_BY_ID_SUCCESS = 'DELETE_SAVED_STOCK_DETAILS_BY_ID_SUCCESS';